[package]
name = "peerbeam-sync"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
peerbeam-browse = { path = "../peerbeam-browse" }
peerbeam-domain = { workspace = true }
tracing = { workspace = true }
async-trait = { workspace = true }
chrono = { workspace = true }
bytes = { workspace = true }
peerbeam-chunk = { path = "../peerbeam-chunk" }
serde = { workspace = true }
sha2 = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
peerbeam-appstore-fs = { path = "../peerbeam-appstore-fs" }
peerbeam-crypto = { path = "../peerbeam-crypto" }
tempfile = { workspace = true }
tokio = { workspace = true }
