[package]
name = "peerbeam-spaces"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
peerbeam-domain = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
rand = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }

[dev-dependencies]
peerbeam-crypto = { path = "../peerbeam-crypto" }
peerbeam-appstore-fs = { path = "../peerbeam-appstore-fs" }
peerbeam-trust-fs = { path = "../peerbeam-trust-fs" }
chrono = { workspace = true }
tempfile = { workspace = true }
