//! Content-defined chunking: splitting a file so that editing it barely changes
//! the pieces.
//!
//! # Why not fixed-size blocks
//!
//! Cut a file every 64 KiB and inserting one byte at the front shifts every
//! boundary, so every block hash changes and the whole file is "new". That is
//! the difference between sending a one-line edit and re-sending a gigabyte.
//!
//! Instead the boundaries are chosen by **content**: a rolling hash runs over
//! the bytes and a cut is made wherever its low bits hit a fixed pattern. Insert
//! a byte and only the chunk containing it changes — the boundaries after it
//! land on the same byte sequences they did before, so every later chunk keeps
//! its identity.
//!
//! # The rolling hash
//!
//! A Gear hash: one table lookup and a shift per byte. It is *not* a
//! cryptographic hash and is never used as one — chunk **identity** is
//! SHA-256 over the chunk's bytes ([`Chunk::hash`]). The rolling hash only
//! decides where to cut, so an attacker who controls it can make chunking
//! inefficient, never wrong: the content hash still has to match.

use serde::{Deserialize, Serialize};
use sha2::{Digest, Sha256};

/// Smallest chunk the splitter will emit.
///
/// Without a floor, a run of bytes that happens to satisfy the cut mask
/// repeatedly would produce a swarm of tiny chunks, and the per-chunk overhead
/// would cost more than the deduplication saves.
pub const MIN_CHUNK: usize = 16 * 1024;

/// Target average chunk size — the cut mask is derived from it.
pub const AVG_CHUNK: usize = 64 * 1024;

/// Largest chunk before a cut is forced.
///
/// A ceiling bounds the memory a single chunk can take and stops a file whose
/// content never triggers the mask (long runs of one byte, say) from becoming
/// one enormous chunk.
pub const MAX_CHUNK: usize = 256 * 1024;

/// Bits compared against the mask. `AVG_CHUNK` is a power of two, so this is
/// its log — a cut happens on average once every `AVG_CHUNK` bytes.
const MASK_BITS: u32 = AVG_CHUNK.trailing_zeros();
const MASK: u64 = (1u64 << MASK_BITS) - 1;

/// One piece of a file.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct Chunk {
    /// Byte offset in the file.
    pub offset: u64,
    pub len: u32,
    /// SHA-256 of the chunk's bytes, hex. **This** is the chunk's identity —
    /// the rolling hash only chose where it starts and ends.
    pub hash: String,
}

/// Split `data` into content-defined chunks.
///
/// Deterministic: the same bytes always produce the same chunks, on any machine
/// and any build. Two peers that disagreed about boundaries would share nothing,
/// so this is a compatibility guarantee, not an implementation detail.
#[must_use]
pub fn split(data: &[u8]) -> Vec<Chunk> {
    let mut out = Vec::new();
    let mut start = 0usize;
    while start < data.len() {
        let end = next_boundary(&data[start..]) + start;
        out.push(Chunk {
            offset: start as u64,
            len: (end - start) as u32,
            hash: hash(&data[start..end]),
        });
        start = end;
    }
    out
}

/// Where the next chunk ends, relative to the start of `data`.
///
/// Split out so the boundary rule can be tested on its own: it is the part two
/// peers must agree on exactly.
#[must_use]
fn next_boundary(data: &[u8]) -> usize {
    if data.len() <= MIN_CHUNK {
        return data.len();
    }
    let limit = data.len().min(MAX_CHUNK);
    let mut digest: u64 = 0;
    // Start hashing at MIN_CHUNK: bytes before the floor can never produce a
    // cut, so rolling over them would only cost time. The window still covers
    // every byte that can *influence* a boundary.
    for i in MIN_CHUNK..limit {
        digest = (digest << 1).wrapping_add(GEAR[data[i] as usize]);
        if digest & MASK == 0 {
            return i + 1;
        }
    }
    limit
}

/// SHA-256 of some bytes, hex.
#[must_use]
pub fn hash(data: &[u8]) -> String {
    use std::fmt::Write;
    let digest = Sha256::digest(data);
    let mut s = String::with_capacity(64);
    for b in digest {
        let _ = write!(s, "{b:02x}");
    }
    s
}

/// The Gear table: one pseudo-random 64-bit value per byte value.
///
/// Generated by a fixed linear congruential sequence rather than stored as 256
/// literals — the values only need to be well-spread and **identical on every
/// build**, and a formula that can be read in four lines is easier to trust
/// than a wall of constants nobody can verify.
static GEAR: [u64; 256] = build_gear();

const fn build_gear() -> [u64; 256] {
    let mut table = [0u64; 256];
    // Knuth's LCG constants; any full-period generator would do.
    let mut state: u64 = 0x0123_4567_89ab_cdef;
    let mut i = 0;
    while i < 256 {
        state = state
            .wrapping_mul(6364136223846793005)
            .wrapping_add(1442695040888963407);
        table[i] = state;
        i += 1;
    }
    table
}

#[cfg(test)]
mod tests {
    use super::*;

    fn data(n: usize, seed: u8) -> Vec<u8> {
        // Deterministic pseudo-random bytes: real content, no test flake.
        let mut v = Vec::with_capacity(n);
        let mut x = seed as u32 | 1;
        for _ in 0..n {
            x = x.wrapping_mul(1664525).wrapping_add(1013904223);
            v.push((x >> 16) as u8);
        }
        v
    }

    #[test]
    fn chunks_cover_the_file_exactly_once() {
        let d = data(1_000_000, 7);
        let chunks = split(&d);
        assert!(!chunks.is_empty());
        let mut expected = 0u64;
        for c in &chunks {
            assert_eq!(c.offset, expected, "a gap or overlap between chunks");
            expected += u64::from(c.len);
        }
        assert_eq!(expected, d.len() as u64, "chunks do not cover the file");
    }

    #[test]
    fn splitting_is_deterministic() {
        // Two peers that disagreed about boundaries would share nothing.
        let d = data(500_000, 3);
        assert_eq!(split(&d), split(&d));
    }

    #[test]
    fn chunk_sizes_respect_the_floor_and_ceiling() {
        let d = data(2_000_000, 11);
        let chunks = split(&d);
        for c in chunks.iter().take(chunks.len() - 1) {
            assert!(
                c.len as usize >= MIN_CHUNK,
                "chunk of {} is below the floor",
                c.len
            );
            assert!(
                c.len as usize <= MAX_CHUNK,
                "chunk of {} is above the ceiling",
                c.len
            );
        }
    }

    /// **The whole point.** Insert a byte at the front and a fixed-size splitter
    /// would report every block as changed. Content-defined boundaries must
    /// leave the later chunks alone.
    #[test]
    fn inserting_a_byte_at_the_front_changes_only_the_chunks_near_it() {
        let original = data(1_000_000, 5);
        let mut edited = vec![0xAAu8];
        edited.extend_from_slice(&original);

        let before = split(&original);
        let after = split(&edited);

        let old: std::collections::HashSet<&String> = before.iter().map(|c| &c.hash).collect();
        let shared = after.iter().filter(|c| old.contains(&c.hash)).count();
        assert!(
            shared * 10 >= before.len() * 8,
            "only {shared} of {} chunks survived a one-byte insert — the \
             boundaries are shifting like fixed-size blocks",
            before.len()
        );
    }

    #[test]
    fn editing_the_middle_leaves_both_ends_intact() {
        let original = data(1_000_000, 9);
        let mut edited = original.clone();
        for b in edited.iter_mut().skip(500_000).take(64) {
            *b ^= 0xFF;
        }
        let before = split(&original);
        let after = split(&edited);
        let old: std::collections::HashSet<&String> = before.iter().map(|c| &c.hash).collect();
        let changed = after.iter().filter(|c| !old.contains(&c.hash)).count();
        assert!(
            changed <= 3,
            "{changed} chunks changed for a 64-byte edit in the middle"
        );
    }

    #[test]
    fn a_short_file_is_one_chunk() {
        let d = data(100, 1);
        let chunks = split(&d);
        assert_eq!(chunks.len(), 1);
        assert_eq!(chunks[0].len, 100);
        assert_eq!(chunks[0].offset, 0);
    }

    #[test]
    fn an_empty_file_has_no_chunks() {
        assert!(split(&[]).is_empty());
    }

    /// What makes deduplication work: identity is content, not position.
    ///
    /// The shared region has to be **comfortably larger than one average
    /// chunk** for this to mean anything. A block smaller than `AVG_CHUNK` gets
    /// absorbed into a chunk that spans the junction with its neighbour, so it
    /// shares no hash — not a flaw in the splitter, but a fact about
    /// content-defined chunking that a too-small fixture hides rather than
    /// tests.
    #[test]
    fn identical_content_at_different_offsets_shares_a_hash() {
        let block = data(AVG_CHUNK * 16, 4);
        let a = split(&block);
        let mut shifted = data(AVG_CHUNK * 3 + 7, 8);
        shifted.extend_from_slice(&block);
        let b = split(&shifted);

        let left: std::collections::HashSet<&String> = a.iter().map(|c| &c.hash).collect();
        let shared = b.iter().filter(|c| left.contains(&c.hash)).count();
        assert!(
            shared >= a.len() / 2,
            "only {shared} of {} chunks were shared after shifting the block by \
             an arbitrary offset — identity is tracking position, not content",
            a.len()
        );
    }

    #[test]
    fn a_run_of_one_byte_is_cut_at_the_ceiling_rather_than_growing_forever() {
        // Content that never satisfies the mask must still terminate.
        let d = vec![0u8; MAX_CHUNK * 3];
        let chunks = split(&d);
        assert!(chunks.len() >= 3);
        for c in &chunks {
            assert!(c.len as usize <= MAX_CHUNK);
        }
    }

    #[test]
    fn the_gear_table_is_well_spread_and_fixed() {
        // Identical on every build, or two peers chunk differently.
        let distinct: std::collections::HashSet<u64> = GEAR.iter().copied().collect();
        assert_eq!(distinct.len(), 256, "the table has duplicate entries");
        assert_ne!(GEAR[0], 0);
    }
}
